version: 2

run:
  deadline: 1m
  tests: true

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - bin$
    - \.git$
    - misc$
    - spec$
    - pkg$
    - common$
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"
    - "always receives"
    - "parameter .* is always"
    - "comment on exported .* should be of the form"

linters-settings:
  errcheck:
    check-blank: true
  govet: {}  
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 30
  dupl:
    threshold: 200
  nakedret:
    max-func-lines: 50
  funlen:
    lines: 80
    statements: 50

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - unused
    - staticcheck
    - dupl
  fast: false

output:
  format: colored-line-number  
